### ISSUE TITLE
some bugs cause crash in bot

### ISSUE THREAD

**Issue by GoldExynos** [callsmusic/remix#61] opened 2021-09-14 08:36 UTC
[remix.log](https://github.com/callsmusic/remix/files/7160221/remix.log)
Hi.
I installed the bot on my Ubuntu 18.04 server and It works properly but there is some bugs that cause crash and stopping the process. When the music is playing on voice chat, if you send /skip command or let the music to finish automatically, it returns bunch of errors that I collect it into a file and I attached it to this post.
I also installed the latest version of npm.
I really appreciate it, if you fix it ASAP <3

**Comment by rojserbest** [comment] 2021-09-14 09:04
Thanks for reporting it. Can you provide exact reproduction steps of that error? That will be super useful.

**Comment by GoldExynos** [comment] 2021-09-14 09:06
> Thanks for reporting it. Can you provide exact reproduction steps of that error? That will be super useful.

**Comment by GoldExynos** [comment] 2021-09-14 09:15
> Thanks for reporting it. Can you provide exact reproduction steps of that error? That will be super useful.

It's my pleasure.
Steps that cause crash:
1- Running bot with command `npm start`.
2- Reply on a music in group and send /play command.
3- Send /skip command to finish the music (or let the music to finish automatically) and let the bot to leave the voice chat automatically after finishing music.
4- after that, bot crash immediately and cause errors.
note: If there is only one music playing on the voice chat, this problem happens. But if there are more than one music on the list, the bot works properly and play the next song until the end.(The main problem is finishing musics and leaving the voice chat.)

**Comment by rojserbest** [comment] 2021-09-14 11:08
@GoldExynos I tried to reproduce it but couldn't get that error.

Here's what I've done:
- Started the bot with `npm start`.
- Replied a YouTube URL with `/play`.
- Used `/skip`.

**Comment by GoldExynos** [comment] 2021-09-14 11:23
> @GoldExynos I tried to reproduce it but couldn't get that error.
> 
> Here's what I've done:
> 
> * Started the bot with `npm start`.
> * Replied a YouTube URL with `/play`.
> * Used `/skip`.

Hi. 
Notice that I reply to a music file that is in the group.

**Comment by rojserbest** [comment] 2021-09-14 15:43
Closing this because it doesn’t provide enough information.

**Closed by rojserbest** 2021-09-14 15:43 UTC
Labels: bug
